spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_alessiopinna
    username: freedb_apinna
    password: ?P$6$?&mK6gMRxf
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 870651648800-pq8mbb5285trh0hfdlbfub2u24unkt8f.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
